[workspace]
resolver = "2"
members = [ 
    "eth-service",
    "gateway",
]

# override some release profile options
[profile.release]
strip = true # full sanitize symbols
panic = "abort" # abort instread of unwind
lto = "thin" # some link time optimizations
